// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box': string;
  'container': string;
  'label': string;
  'logo': string;
  'logoWrapper': string;
  'text': string;
  'title': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
