// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'button': string;
  'container': string;
  'label': string;
  'logo': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
